[versions]
kotlin = "2.1.10"
kotest = "5.9.0"
slf4j = "2.0.16"
logback = "1.5.17"

[libraries]
kotlin-compiler-embeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
kotest-runner = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

[bundles]
kotest = ["kotest-runner", "kotest-assertions"]
logger = ["slf4j-api", "logback-classic"]